creation_rules:
  - kms: "arn:aws:kms:us-east-1:xxxxxxxx:key/xxxxxxxx"  # your kms key 
    encrypted_regex: '^(data|stringData)$'   # regex to filter your encrypted data
    path_regex: '.*\.(yaml|yml|json)$' # regex the file type
